# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gustav/source/twcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gustav/source/twcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/local/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gustav/source/twcpp/CMakeFiles /home/gustav/source/twcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gustav/source/twcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named /usr/local/include

# Build rule for target.
/usr/local/include: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 /usr/local/include
.PHONY : /usr/local/include

# fast build rule for target.
/usr/local/include/fast:
	$(MAKE) -f CMakeFiles//usr/local/include.dir/build.make CMakeFiles//usr/local/include.dir/build
.PHONY : /usr/local/include/fast

#=============================================================================
# Target rules for targets named tw

# Build rule for target.
tw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tw
.PHONY : tw

# fast build rule for target.
tw/fast:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/build
.PHONY : tw/fast

maintest.o: maintest.cpp.o
.PHONY : maintest.o

# target to build an object file
maintest.cpp.o:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/maintest.cpp.o
.PHONY : maintest.cpp.o

maintest.i: maintest.cpp.i
.PHONY : maintest.i

# target to preprocess a source file
maintest.cpp.i:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/maintest.cpp.i
.PHONY : maintest.cpp.i

maintest.s: maintest.cpp.s
.PHONY : maintest.s

# target to generate assembly for a file
maintest.cpp.s:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/maintest.cpp.s
.PHONY : maintest.cpp.s

tweet.o: tweet.cpp.o
.PHONY : tweet.o

# target to build an object file
tweet.cpp.o:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/tweet.cpp.o
.PHONY : tweet.cpp.o

tweet.i: tweet.cpp.i
.PHONY : tweet.i

# target to preprocess a source file
tweet.cpp.i:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/tweet.cpp.i
.PHONY : tweet.cpp.i

tweet.s: tweet.cpp.s
.PHONY : tweet.s

# target to generate assembly for a file
tweet.cpp.s:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/tweet.cpp.s
.PHONY : tweet.cpp.s

twitter.o: twitter.cpp.o
.PHONY : twitter.o

# target to build an object file
twitter.cpp.o:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/twitter.cpp.o
.PHONY : twitter.cpp.o

twitter.i: twitter.cpp.i
.PHONY : twitter.i

# target to preprocess a source file
twitter.cpp.i:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/twitter.cpp.i
.PHONY : twitter.cpp.i

twitter.s: twitter.cpp.s
.PHONY : twitter.s

# target to generate assembly for a file
twitter.cpp.s:
	$(MAKE) -f CMakeFiles/tw.dir/build.make CMakeFiles/tw.dir/twitter.cpp.s
.PHONY : twitter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... /usr/local/include"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tw"
	@echo "... maintest.o"
	@echo "... maintest.i"
	@echo "... maintest.s"
	@echo "... tweet.o"
	@echo "... tweet.i"
	@echo "... tweet.s"
	@echo "... twitter.o"
	@echo "... twitter.i"
	@echo "... twitter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

